parserOptions:
  project:
    - './tsconfig.json'
    - './tsconfig.cypress.json'
extends:
  - airbnb
  - airbnb/hooks
  - airbnb-typescript
  - plugin:prettier/recommended
rules:
  # base rules
  no-return-assign: off

  # typescript rules
  '@typescript-eslint/prefer-default-export': 'off'
  '@typescript-eslint/lines-between-class-members': 'off'

  # react rules
  'react/function-component-definition':
    - 2
    - namedComponents: 'arrow-function'
  'react/jsx-no-useless-fragment': 'off'
  'react/jsx-props-no-spreading': 'off'

  # import rules
  'import/prefer-default-export': 'off'
  'import/no-extraneous-dependencies':
    - error
    - devDependencies:
      - '**/*.cy.ts'
      - '*.config.ts'
  'import/order':
    - 'error'
    - 'newlines-between': 'always'
      groups:
        - 'builtin'
        - 'external'
        - 'internal'
        - 'parent'
        - 'sibling'
        - 'index'